services: 
  stucon_server:
    build: .
    container_name: stucon_server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./public:/app/public
    working_dir: /app/cmd
    command: ./stucon
networks:
  deployment_stucon:
    external: true

